#!/usr/bin/env bash

set -eo pipefail

BATTERY=$(acpi | head -n 1)
CHARGE=$(echo ${BATTERY} | awk '{print $4}' | sed 's/[^0-9]//g')
STATUS=$(echo ${BATTERY} | awk '{print $3}' | sed 's/[^A-Za-z]//g')

if [ ${STATUS} == "Discharging" ]; then
	if [ "${CHARGE}" == 100 ]; then
		echo "󰁹 ${CHARGE}%"
		exit 0
	elif [ "${CHARGE}" -lt 100 ] && [ "${CHARGE}" -gt 50 ]; then
		echo "󰂁 ${CHARGE}%"
		exit 0
	elif [ "${CHARGE}" == 50 ]; then
		echo "󰁾 ${CHARGE}%"
		exit 0
	elif [ "${CHARGE}" -lt 50 ] && [ "${CHARGE}" -gt 14 ]; then
		echo "󰁼 ${CHARGE}%"
		exit 0
	else
		echo "󱃍 ${CHARGE}%"
		exit 0
	fi
else
	if [ "${CHARGE}" == 100 ]; then
		echo "󰂅 ${CHARGE}%"
		exit 0
	elif [ "${CHARGE}" -lt 100 ] && [ "${CHARGE}" -gt 50 ]; then
		echo "󰂊 ${CHARGE}%"
		exit 0
	elif [ "${CHARGE}" == 50 ]; then
		echo "󰢝 ${CHARGE}%"
		exit 0
	elif [ "${CHARGE}" -lt 50 ] && [ "${CHARGE}" -gt 14 ]; then
		echo "󰂇 ${CHARGE}%"
		exit 0
	else
		echo "󰢜 ${CHARGE}%"
		exit 0
	fi
fi
