#!/usr/bin/env bash

set -e

VOLUME=$(volumectl get)
if [ "${VOLUME}" == "mute" ]; then
	echo " mute"
	exit 0
fi

if [ "${VOLUME::-1}" -gt 49 ]; then
	echo " ${VOLUME}"
elif [ "${VOLUME::-1}" -gt 0 ]; then
	echo " ${VOLUME}"
fi
