#!/usr/bin/env bash

set -o pipefail

WIFI_INTERFACE=$(ip link | grep "wl" | awk '{print $2}' | sed 's/[^a-zA-Z0-9]//g')

OPERSTATE=$(cat /sys/class/net/${WIFI_INTERFACE}/operstate)
if [ "${OPERSTATE}" == "down" ]; then
	echo "down"
	exit 0
fi

WIFI=$(netctl list | grep "*" | awk '{print $2}')
if [[ -z ${WIFI} ]]; then
	echo "up"
	exit 0
fi

echo "${WIFI}"
